### ISSUE TITLE
Not able to access after starting. 

### ISSUE THREAD

**Issue by leonard4546** [kannibalox/PtpUploader#17]
I'm trying to run this on my seedbox. I started it using given command but not able to acces at http://seedbox_ip:8000 . Port 8000 is open.

is there any method to check for logs. and is it possible to change port like old version

**Comment by kannibalox** [comment]
By default it only listens on localhost (127.0.0.1), but you can change both the bind address and the port by adding them after `runuploader`, e.g. `PtpUploader runuploader 0.0.0.0:12345`

Only individual job logs are saved to disk, so the easiest way to save the main output would be to just append it to a file, e.g. `PtpUploader runuploader 2>&1 >> /home/example/ptpuploader.log`
If you want to get fancier, you can even override the default Django logging config in `~/.config/ptpuploader/config.yml`:
```yml
# At the end of the file
LOGGING: {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "root_formatter": {
            "format": "%(asctime)-15s %(levelname)-5s %(name)-11s %(message)s"
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "root_formatter",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "/home/example/ptpuploader.log",
            "formatter": "root_formatter",
        },
    },
    "loggers": {
        "": {
            "handlers": [
                "console",
            ],
            "level": "INFO",
            "propagate": True,
        }
    },
}
```
